const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const threeRoot = path.dirname(require.resolve('three/package.json'));
let html = fs.readFileSync(path.join(root, 'viewer/room.html'), 'utf8');
const scripts = ['build/three.min.js', 'examples/js/controls/OrbitControls.js'];
for (const script of scripts) {
  const code = fs.readFileSync(path.join(threeRoot, script), 'utf8').replace(/<\/script/gi, '<\\/script');
  html = html.replace(/<script src="[^"]+"><\/script>/, () => '<script>' + code + '</script>');
}
fs.mkdirSync(path.join(root, 'generated'), { recursive: true });
fs.writeFileSync(path.join(root, 'generated/viewerHtml.js'), '// Generated by scripts/build-viewer.cjs.\nexport const viewerHtml = ' + JSON.stringify(html) + ';\n');
console.log('Bundled offline room viewer.');
